@startuml
left to right direction
skinparam packageStyle rectangle
actor User

rectangle lastminute-service {
  (Kombi durchsuchen) -- User
  (Kombi aktualisieren) -- User
  (Kombi buchen) as (KB) <<Wunschziel>>
  (KB) -- User
  (Kombi aktualisieren) -> (Kombi speichern)
}

rectangle airline-service {
  (Flugdaten anbieten) <-- (Kombi aktualisieren) : uses
  (Flugdaten hinterlegen)
}

rectangle hotel-service {
  (unbelegte Zimmer hinterlegen)
  (Freie Zimmerdaten anbieten) <-- (Kombi aktualisieren) : uses
}

note "nur über einen Datebankzugriff" as N1
(Flugdaten hinterlegen) .. N1
(unbelegte Zimmer hinterlegen) .. N1
@enduml