@startuml
left to right direction
skinparam packageStyle rectangle
actor lastminute << Application >>
actor airline << Application >>
rectangle airline-service {
  (Flugdaten hinterlegen) -- airline
  (Flugdaten abholen) -- lastminute
  (Sitzplatz reservieren) -- lastminute
}

note "nur über einen Datebankzugriff" as N1
(Flugdaten hinterlegen) .. N1
@enduml