@startuml
left to right direction
skinparam packageStyle rectangle
actor lastminute << Application >>
actor hotel << Application >>
rectangle hotel-service {
  (unbelegte Zimmer hinterlegen) -- hotel
  (Freie Zimmerdaten abholen) -- lastminute
  (Zimmer reservieren) -- lastminute
}

note "nur über einen Datebankzugriff" as N1
(unbelegte Zimmer hinterlegen) .. N1
@enduml